<?php

namespace Sidep\Http\Requests;

use Sidep\Http\Requests\Request;

class FormEditarServidorPublico extends Request
{
    protected $rules = [
        'nombre'           => 'required',
        'paterno'          => 'required',
        'materno'          => 'required',
        'fechaNacimiento'  => 'date_format:d/m/Y',
        'curp'             => 'required|max:18|min:18',
        'rfc'              => 'required|max:13|min:10',
        'email'            => 'email',
        'estadoCivil'      => 'required',
        'calle'            => 'required',
        'noExterior'       => 'required',
        'coloniaLocalidad' => 'required',
        'municipio'        => 'required',
    ];

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return $this->rules;
    }

    public function response(array $errors)
    {
        return parent::response($errors); // TODO: Change the autogenerated stub
    }
}