<?php

namespace DoctrineProxies\__CG__\Sidep\Dominio\ServidoresPublicos;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Declaracion extends \Sidep\Dominio\ServidoresPublicos\Declaracion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'id', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'declaracionTipo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'estatus', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'fechaGeneracion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'fechaPlazo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'realizada', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'observacion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'tieneRequerimiento', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'requerimiento', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'sancionada', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'fechaEnvioFuncionPublica', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'numeroOficioSancion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'encargo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'oficioRequerimiento', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'requerimientoAbierto'];
        }

        return ['__isInitialized__', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'id', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'declaracionTipo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'estatus', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'fechaGeneracion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'fechaPlazo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'realizada', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'observacion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'tieneRequerimiento', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'requerimiento', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'sancionada', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'fechaEnvioFuncionPublica', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'numeroOficioSancion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'encargo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'oficioRequerimiento', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Declaracion' . "\0" . 'requerimientoAbierto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Declaracion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaGeneracion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaGeneracion', []);

        return parent::getFechaGeneracion();
    }

    /**
     * {@inheritDoc}
     */
    public function estatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'estatus', []);

        return parent::estatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPlazo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPlazo', []);

        return parent::getFechaPlazo();
    }

    /**
     * {@inheritDoc}
     */
    public function realizada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'realizada', []);

        return parent::realizada();
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', []);

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function tieneRequerimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneRequerimiento', []);

        return parent::tieneRequerimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function getRequerimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequerimiento', []);

        return parent::getRequerimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function sancionada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sancionada', []);

        return parent::sancionada();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaEnvioFuncionPublica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaEnvioFuncionPublica', []);

        return parent::getFechaEnvioFuncionPublica();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaracionTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeclaracionTipo', []);

        return parent::getDeclaracionTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function declaracionTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'declaracionTipo', []);

        return parent::declaracionTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function getEncargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncargo', []);

        return parent::getEncargo();
    }

    /**
     * {@inheritDoc}
     */
    public function getOficioRequerimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOficioRequerimiento', []);

        return parent::getOficioRequerimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function generarFechaDeCumplimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generarFechaDeCumplimiento', []);

        return parent::generarFechaDeCumplimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function marcarComoOmiso(\DateTime $fecha, \Sidep\Dominio\Folios\Folio $folio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'marcarComoOmiso', [$fecha, $folio]);

        return parent::marcarComoOmiso($fecha, $folio);
    }

    /**
     * {@inheritDoc}
     */
    public function marcarRetornoDeRequerimiento(\Sidep\Dominio\Declaraciones\OficioRequerimiento $oficio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'marcarRetornoDeRequerimiento', [$oficio]);

        return parent::marcarRetornoDeRequerimiento($oficio);
    }

    /**
     * {@inheritDoc}
     */
    public function desmarcarOmiso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'desmarcarOmiso', []);

        return parent::desmarcarOmiso();
    }

    /**
     * {@inheritDoc}
     */
    public function seHaRegresadoElRequerimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'seHaRegresadoElRequerimiento', []);

        return parent::seHaRegresadoElRequerimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function desmarcarRecepcionRequerimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'desmarcarRecepcionRequerimiento', []);

        return parent::desmarcarRecepcionRequerimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function requerimientoAbierto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'requerimientoAbierto', []);

        return parent::requerimientoAbierto();
    }

    /**
     * {@inheritDoc}
     */
    public function seAbrioElRequerimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'seAbrioElRequerimiento', []);

        return parent::seAbrioElRequerimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function marcarEnvioASFP(\DateTime $fecha, \Sidep\Dominio\Folios\Folio $folio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'marcarEnvioASFP', [$fecha, $folio]);

        return parent::marcarEnvioASFP($fecha, $folio);
    }

    /**
     * {@inheritDoc}
     */
    public function removerSancion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removerSancion', []);

        return parent::removerSancion();
    }

}
