<?php

namespace DoctrineProxies\__CG__\Sidep\Dominio\ServidoresPublicos;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Encargo extends \Sidep\Dominio\ServidoresPublicos\Encargo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'id', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'servidorPublico', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'adscripcion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'cuentaAcceso', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'puesto', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'fechaAlta', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'activo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'usuarioSidep', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'tipoUsuario', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'dependencia', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'movimientos', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'declaraciones', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'privilegios', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'exento'];
        }

        return ['__isInitialized__', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'id', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'servidorPublico', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'adscripcion', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'cuentaAcceso', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'puesto', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'fechaAlta', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'activo', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'usuarioSidep', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'tipoUsuario', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'dependencia', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'movimientos', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'declaraciones', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'privilegios', '' . "\0" . 'Sidep\\Dominio\\ServidoresPublicos\\Encargo' . "\0" . 'exento'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Encargo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getServidorPublico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServidorPublico', []);

        return parent::getServidorPublico();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdscripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdscripcion', []);

        return parent::getAdscripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function getCuentaAcceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCuentaAcceso', []);

        return parent::getCuentaAcceso();
    }

    /**
     * {@inheritDoc}
     */
    public function getPuesto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPuesto', []);

        return parent::getPuesto();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function estaActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'estaActivo', []);

        return parent::estaActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function esUsuarioSidep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'esUsuarioSidep', []);

        return parent::esUsuarioSidep();
    }

    /**
     * {@inheritDoc}
     */
    public function tipoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tipoUsuario', []);

        return parent::tipoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function estaExento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'estaExento', []);

        return parent::estaExento();
    }

    /**
     * {@inheritDoc}
     */
    public function getExento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExento', []);

        return parent::getExento();
    }

    /**
     * {@inheritDoc}
     */
    public function login($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'login', [$password]);

        return parent::login($password);
    }

    /**
     * {@inheritDoc}
     */
    public function servidorPublico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'servidorPublico', []);

        return parent::servidorPublico();
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientos', []);

        return parent::getMovimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeclaraciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeclaraciones', []);

        return parent::getDeclaraciones();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivilegios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivilegios', []);

        return parent::getPrivilegios();
    }

    /**
     * {@inheritDoc}
     */
    public function inicializarModulos(\Sidep\Dominio\Listas\IColeccion $privilegios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'inicializarModulos', [$privilegios]);

        return parent::inicializarModulos($privilegios);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependencia', []);

        return parent::getDependencia();
    }

    /**
     * {@inheritDoc}
     */
    public function generarCuentaDeAcceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generarCuentaDeAcceso', []);

        return parent::generarCuentaDeAcceso();
    }

    /**
     * {@inheritDoc}
     */
    public function tieneCuentaDeAccesoGenerada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneCuentaDeAccesoGenerada', []);

        return parent::tieneCuentaDeAccesoGenerada();
    }

    /**
     * {@inheritDoc}
     */
    public function alta($exento, \Sidep\Dominio\ServidoresPublicos\Movimiento $movimiento, \Sidep\Dominio\ServidoresPublicos\Declaracion $declaracion, $fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'alta', [$exento, $movimiento, $declaracion, $fechaAlta]);

        return parent::alta($exento, $movimiento, $declaracion, $fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function baja(\Sidep\Dominio\ServidoresPublicos\Movimiento $movimiento, \Sidep\Dominio\ServidoresPublicos\Declaracion $declaracion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'baja', [$movimiento, $declaracion]);

        return parent::baja($movimiento, $declaracion);
    }

    /**
     * {@inheritDoc}
     */
    public function tieneEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneEmail', []);

        return parent::tieneEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function cambiarAdscripcion($nuevaAdscripcion, \Sidep\Dominio\ServidoresPublicos\Movimiento $movimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cambiarAdscripcion', [$nuevaAdscripcion, $movimiento]);

        return parent::cambiarAdscripcion($nuevaAdscripcion, $movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function recibirPromocion(\Sidep\Dominio\ServidoresPublicos\Puesto $puesto, $adscripcion, \Sidep\Dominio\ServidoresPublicos\Movimiento $movimientoBaja, \Sidep\Dominio\ServidoresPublicos\Movimiento $movimientoAlta, \Sidep\Dominio\ServidoresPublicos\Declaracion $conclusion, \Sidep\Dominio\ServidoresPublicos\Declaracion $inicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'recibirPromocion', [$puesto, $adscripcion, $movimientoBaja, $movimientoAlta, $conclusion, $inicial]);

        return parent::recibirPromocion($puesto, $adscripcion, $movimientoBaja, $movimientoAlta, $conclusion, $inicial);
    }

    /**
     * {@inheritDoc}
     */
    public function obtenerFechaAnteriorAPromocion(\DateTime $fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'obtenerFechaAnteriorAPromocion', [$fecha]);

        return parent::obtenerFechaAnteriorAPromocion($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function tieneMovimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneMovimientos', []);

        return parent::tieneMovimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function obtenerUltimoMovimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'obtenerUltimoMovimiento', []);

        return parent::obtenerUltimoMovimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function elUltimoMovimientoEsBaja()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'elUltimoMovimientoEsBaja', []);

        return parent::elUltimoMovimientoEsBaja();
    }

    /**
     * {@inheritDoc}
     */
    public function elUltimoMovimientoEsPorTerminoEncargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'elUltimoMovimientoEsPorTerminoEncargo', []);

        return parent::elUltimoMovimientoEsPorTerminoEncargo();
    }

    /**
     * {@inheritDoc}
     */
    public function generarUsuarioSidep($usuarioTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generarUsuarioSidep', [$usuarioTipo]);

        return parent::generarUsuarioSidep($usuarioTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function removerPrivilegios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removerPrivilegios', []);

        return parent::removerPrivilegios();
    }

    /**
     * {@inheritDoc}
     */
    public function asignarPrivilegio(\Sidep\Dominio\ServidoresPublicos\EncargoPrivilegio $encargoPrivilegio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'asignarPrivilegio', [$encargoPrivilegio]);

        return parent::asignarPrivilegio($encargoPrivilegio);
    }

    /**
     * {@inheritDoc}
     */
    public function tieneElPrivilegio(\Sidep\Dominio\Usuarios\Modulo $modulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'tieneElPrivilegio', [$modulo]);

        return parent::tieneElPrivilegio($modulo);
    }

}
